# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRBL_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('srv_type', models.CharField(choices=[('P', 'Physical'), ('V', 'Virtual'), ('A', 'Appliance')], max_length=1)),
                ('tier', models.CharField(choices=[('AP', 'Application - Apache, Weblogic, etc'), ('CM', 'Concurrent Manager'), ('DB', 'Database'), ('PX', 'Proxy'), ('NA', 'Not Applicable')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Server_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.HRBL_App')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server')),
            ],
        ),
        migrations.CreateModel(
            name='ServerIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server')),
            ],
        ),
    ]
