# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_app',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.HRBL_App'),
        ),
        migrations.AlterField(
            model_name='server_app',
            name='server_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server'),
        ),
        migrations.AlterField(
            model_name='serverip',
            name='server_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server'),
        ),
    ]
